minor revisions and updates

diff --git a/.github/workflows/create_release.yaml b/.github/workflows/create_release.yaml
--- a/.github/workflows/create_release.yaml
+++ b/.github/workflows/create_release.yaml
@@ -17,19 +17,20 @@ jobs:
 
       # Step 2: Set up Java environment
       - name: Set up Java
-        uses: actions/setup-java@v3
+        uses: actions/setup-java@v4
         with:
           java-version: '17'
           distribution: 'temurin'
 
       # Step 3: Cache Maven dependencies
       - name: Cache Maven dependencies
-        uses: actions/cache@v3
+        uses: actions/cache@v4
         with:
           path: ~/.m2/repository
           key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
           restore-keys: |
             ${{ runner.os }}-maven-
+            ${{ runner.os }}-
 
 
       # Step 4: Build the project
@@ -91,15 +92,17 @@ jobs:
           path: ./target  # Specify the target directory
 
       # Step 5: Verify .vmod file exists
-      - name: Verify .vmod file exists
+      - name: Verify and extract file name
         run: |
           VMOD_FILE=$(find ./target -name '*.vmod' -print -quit)
           if [[ -z "$VMOD_FILE" ]]; then
-          echo "Error: No .vmod file found in ./target directory"
-          exit 1
+            echo "Error: No .vmod file found in ./target directory"
+            exit 1
           fi
-          echo "Found .vmod file: $VMOD_FILE"
+          FILE_NAME=$(basename "$VMOD_FILE")
           echo "VMOD_FILE=$VMOD_FILE" >> $GITHUB_ENV
+          echo "FILE_NAME=$FILE_NAME" >> $GITHUB_ENV
+          echo "Found .vmod file: $VMOD_FILE with name: $FILE_NAME"
 
       # Step 6: Create GitHub Release
       - name: Create GitHub Release
@@ -121,8 +124,8 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ${{ env.VMOD_FILE }}  # Use the dynamically located file
-          asset_name: $(basename ${{ env.VMOD_FILE }})
+          asset_path: ${{ env.VMOD_FILE }}  # Full file path
+          asset_name: ${{ env.FILE_NAME }}  # File name only
           asset_content_type: application/octet-stream
 
 #      - name: Upload target directory as zip
